<Project Sdk="Aspire.AppHost.Sdk/13.3.5">

  <ItemGroup>
    <ProjectReference Include="..\server\SchoolSystemTask.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>59f6848c-3aa6-4c2f-8c18-22fec8215d6a</UserSecretsId>
  </PropertyGroup>

</Project>
